### PR TITLE
Revamped README

### PR DESCRIPTION
**Pull request by TheEvilSkeleton**
The README seemed a bit messed up (bolding for no reason, centering, etc.) so I decided to fix it. Enjoy.

### CODE REVIEW

**Comment by resynth1943** [comment]
Hey! I've contributed to this PR too, so I thought I might as well have my say.

@JohnFawkes It's not common practice to ignore the work of others, especially when they have taken the time to produce this improvement for *your* project. Furthermore, you have failed to submit a reason for your closing. This would be appreciated.

Many thanks,
Synth

**Comment by SJWsAreACancer** [comment]
I have cloned JohnFawkes Font Changer and Fixed it, if anyone would like a link, it is now open source

**Comment by JohnFawkes** [comment]
It's not meant to be open source. That's why the warning in readme. Please remove

**Comment by SJWsAreACancer** [comment]
no thanks. i will be publishing it under a different name. Thank you!

**Comment by JohnFawkes** [comment]
OK then. Dmca incoming

**Comment by SJWsAreACancer** [comment]
Good luck with that, im not from america so i will be ignoring it

**Comment by JohnFawkes** [comment]
You don't have to be from America lol

**Comment by SJWsAreACancer** [comment]
Im form a country that doesnt give a shit about DMCA. its gonna be posted in about 30 mins.

**Comment by SJWsAreACancer** [comment]
i will continue making github accounts and posting it, you cant stop me

**Comment by SJWsAreACancer** [comment]
Since you ignore other peoples contribtions, im ignoring your request

**Comment by SJWsAreACancer** [comment]
Guys, the epo is now live and the Magisk Module can be downloaded. All files are rehosted. Please DM me for private link

**Comment by SJWsAreACancer** [comment]
It is now open source so feel free to contribute

**Comment by SJWsAreACancer** [comment]
Oh i didnt leav a link. DM me on discord. Grim#1806

**Comment by SJWsAreACancer** [comment]
DM me on Discord Grim#1806 for the open source version that works! Exact same code!

**Comment by JohnFawkes** [comment]
You do realize mine is open source right? It's just you aren't allowed to use it in anything else

**Comment by SJWsAreACancer** [comment]
DM me for a version that works! Grim#1806 on Discord

**Comment by SJWsAreACancer** [comment]
DM me for a version that works! Grim#1806 on Discord, works right now!

**Comment by lazerl0rd** [comment]
@resynth I'd like to keep this short cause it's late down (up?) in the UK, so my apologies if I come across too blunt.

You stated that "it isn't common practice to ignore the work of others". I can understand that if a lot of hard work has gone into a PR and there's a bug fix or a new feature, that's quite understandable. However, this PR literally changes the formatting of the repo's README. It isn't anything big. And in terms of responding to PRs like this being "common practice", the truth of the matter is that it actually isn't. If you don't believe me, take a five minute look at Linux's mailing list.
 
I'd like to also pick on your point about others' time being spent on John's project. The be all and end all is that this is *John's project*. Not yours. Not mine. He has all rights to decide what gets added and what doesn't. If you don't like it, you're free to create your own module (*without using his code* as that violates the license).

He also has no requirement or obligation to respond to you. You're didn't buy this Magisk Module. You aren't paying a subscription. People have lives, jobs, and family. They can't always respond at your leisure.

Yes, it would be nice to have a response to why your PR was "ignored" but a polite question would've done the job. Adding "thank you" to the end of a demand doesn't make it any less so. 

I'm not writing this to degrade or insult you, I'm writing this because you seem to be a nice guy - but your misconceptions and or attitudes in this PR were utterly wrong.

@SJWsAreACancer, before you go around throwing statements out your backside like a defensive child please check your information. Yes, you might not live in America but *GitHub* is a registered *US* company. That means they have to abide by US regulations (and so do Discord, for that matter). As a result, *John can DMCA you* as he wishes and whatever you put up will be taken down.

**Comment by SJWsAreACancer** [comment]
Well my repo is up!@ Good luck taking it down! If you can find it, that is!

**Comment by SJWsAreACancer** [comment]
new repo is up! DM me at Grim#1806, Github might be a US based company but that implies i hosted it on Github, which i did not! Whats your move now, smartass!

**Pull request closed without merging**
