### PR TITLE
Remove the warning?

### PR DESCRIPTION
**Pull request by resynth1943**
To be honest, it comes off as highly authoritative. I would suggest moving it to the bottom, and not highlighting it.

And the "yes, that's right" sentence really does not help. In most cases, the reader is not going to care if you are right, they just wish to use the module.

### CODE REVIEW

**Comment by resynth1943** [comment]
Also, excuse me, but where is the hub for issues?

**Comment by JohnFawkes** [comment]
The only reason I put the yes part is because I've been attacked by numerous people for supposedly not being open source when the code is 100% open source and alot of people actually think modules have to be gpl or even open source to be on the repo when they dont

**Comment by JohnFawkes** [comment]
Also I disabled issues again for the same reason of being attacked

**Comment by resynth1943** [comment]
> The only reason I put the yes part is because I've been attacked by numerous people for supposedly not being open source when the code is 100% open source and alot of people actually think modules have to be gpl or even open source to be on the repo when they dont

Technically it's not open-source, because the user has no actual rights over the source code. Apologies, but if many people are suggesting you open-source this module, why aren't you? What harm would making this module open-source do?

I'm curious about your reasoning that this module should not be open-sourced. Also, who said anything about GPL? It's up to the maintainer to choose a license.

Why?

By not giving users any rights, you are effectively stifling the innovation of your module. That's sad, and really fails to respect the social aspect of sharing source code.

**Comment by resynth1943** [comment]
> Also I disabled issues again for the same reason of being attacked

How are users supposed to notify you that your module is now broken?

**Comment by JohnFawkes** [comment]
The module isn't broken. It's under maintenance. There's also clearly in the readme a telegram group for issues and support

**Comment by JohnFawkes** [comment]
There's a huge difference between free and open source. The code itself is open source. I'm not gunna argue anymore over this. I've said what I wanted to and said how I feel. I'm not gunna give this a license. End of discussion

**Pull request closed without merging**
