### PR TITLE
Fix tr

### PR DESCRIPTION
**Pull request by Akilesh-T**
Now, choice2 won't have the choice number and choice name.

### CODE REVIEW

**Comment by JohnFawkes** [comment]
fixed

**Comment by SJWsAreACancer** [comment]
DM me on Discord Grim#1806 for the open source version that works! Exact same code!

**Comment by SJWsAreACancer** [comment]
DM me for a version that works! Grim#1806 on Discord

**Comment by SJWsAreACancer** [comment]
DM me for a version that works! Grim#1806 on Discord

**Comment by SJWsAreACancer** [comment]
DM me for a version that works! Grim#1806 on Discord

**Comment by SJWsAreACancer** [comment]
DM me for a version that works! Grim#1806 on Discord

**Comment by SJWsAreACancer** [comment]
DM me for a version that works! Grim#1806 on Discord

**Comment by SJWsAreACancer** [comment]
Nice, 4 people are already using mine!

**Comment by SJWsAreACancer** [comment]
REPO IS UP FAGGOTS! Goopd luck!

**Comment by SJWsAreACancer** [comment]
JohnFawkes is a faggot

**Comment by SJWsAreACancer** [comment]
Faggot john fawks

**Comment by SJWsAreACancer** [comment]
@lazerl0rd, what up, my repo is up! you cant take it down! AHAHHAHAHHAH! Neither can he!

**Comment by SJWsAreACancer** [comment]
Yo, I have put my repo up on Github! See it now!

**Pull request closed without merging**
